version: '3.4'

volumes:
    pandemiao-conf:
    pandemiao-data:
    pandemiao-logs:
    pandemiao-plugins:

services:
  pandemiao-db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - 7474:7474
      - 6477:6477
      - 7687:7687
    volumes:
      - pandemiao-conf:/conf
      - pandemiao-data:/data
      - pandemiao-logs:/logs
      - pandemiao-plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_mode=CORE
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
  pandemiao:
    build: .
    links:
      - pandemiao-db
    environment:
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - NEO4J_URI=bolt://pandemiao-db
      - NEO4J_ENCRYPTED=Off
    env_file: .env

