name: kitto_linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Checking requirements.txt is ok
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Purring and buying statically typed corn-flakes
        run: pip install flake8 mypy pylint

      - name: Kitto is checking types
        working-directory: ./bot
        run: mypy notify.py listener.py tests/ --strict --follow-imports normal --config-file ../setup.cfg

      - name: Kitto is linting
        run: flake8 .

      - name: Kitto is py-linting
        working-directory: ./bot
        run: pylint listener.py notify.py utils/ tests/

  moby_kitto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Copy .env file
        run: cp .env.example .env
      
      - name: Moby-Kitto loves water
	run: docker-compose build	

       -name: Moby-Kitto ain't scared of tests
	run: sudo docker-compose -f docker-compose.yml -f docker-compose-test.yml up -d pandemiao-db && docker-compose -f docker-compose.yml -f docker-compose-test.yml up  pandemiao-test


