name: kitto_linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
      
    - name: purring and getting dependencies
      run: pip install flake8\
      
    - name: kitto is linting
      run: flake8 bot/*
    
